FROM ubuntu:22.04

# Don't want prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install basic dependencies
RUN echo "Etc/UTC" > /etc/timezone && \
    ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt update && apt install -y \
    build-essential \
    libusb-1.0-0-dev \
    pkg-config \
    locales \
    gawk \
    wget \
    git \
    diffstat \
    unzip \
    texinfo \
    gcc \
    g++ \
    build-essential \
    chrpath \
    socat \
    cpio \
    python3 \
    python3-pip \
    python3-pexpect \
    python3-git \
    python3-jinja2 \
    python3-subunit \
    python3-requests \
    python3-setuptools \
    python3-wheel \
    locales \
    file \
    liblz4-tool \
    zstd \
    bmap-tools \
    xz-utils \
    curl \
    sudo \
    nano \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen en_US.UTF-8

# Set locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install repo tool
RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && \
    chmod a+rx /bin/repo

# Build and install rpiboot
# TODO: USB device passthrough into container not working
#RUN git clone --recurse-submodules --shallow-submodules --depth=1 https://github.com/raspberrypi/usbboot \
#    && cd usbboot \
#    && make install

# Don't require a password for sudo
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00-nopasswd \
    && chmod 0440 /etc/sudoers.d/00-nopasswd
